name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies via poetry
        run: poetry install

      - name: Unbundle test resources
        run: poetry run python3 resources/bundler unbundle
        
      - name: Run unit tests
        run: poetry run pytest --cov=datachef --cov-fail-under=100 tests/

      - name: Run notebook scenarios
        run: poetry run pytest ./scenarios